ControlRemoto/API_control_remoto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('control/', include('apps.control_remoto.urls')),
]

ControlRemoto/apps/control_remoto/urls.py
from django.urls import path

from apps.control_remoto.views.control_remoto.views import *

app_name = 'control_remoto'

urlpatterns = [
    path('control/', ControlRemoto.as_view(), name='control_remoto'),
    path('control_test/', AjustePID.as_view(), name='ajuste_pid'),
    path('nav_robot/', NavViewRobot.as_view(), name='nav_robot'),
]

ControlRemoto/templates/base_body.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Pagina de control remoto">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Control Remoto</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'lib/bootstrap-5.1.3-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fontawesome core CSS -->
    <link href="{% static 'lib/fontawesome-free-5.15.4-web/css/all.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">MISIÓN</h4>
                    <p class="text-muted">Desarrollar, coordinar y fortalecer la investigación en sistemas inteligentes
                        promoviendo tecnologías de vanguardia adaptadas a las necesidades del país y la región.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Contacto</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Síguenos en Twitter</a></li>
                        <li><a href="#" class="text-white">Síguenos en Facebook</a></li>
                        <li><a href="#" class="text-white">Envíanos un email</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>LABSI</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    {% block content %}

    {% endblock %}

</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Volver arriba</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="../getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>


<script src="{% static 'lib/bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/funciones_general.js' %}"></script>

{% block scripts_js %}

{% endblock %}


</body>
</html>

ControlRemoto/templates/body_base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Robot control V2</title>
    <script src="{% static 'js/funciones_general.js' %}"></script>

    {% if debug_value %}
        <!-- Plugin datatables-->
        <link href="{% static 'css/style_dt_bs.css' %}" rel="stylesheet"/>
        <link href="{% static 'lib/admin-bs5/css/styles.css' %}" rel="stylesheet"/>
        <script src="{% static 'lib/fontawesome_v6.1.1/fontawesome_v6.1.1.js' %}" crossorigin="anonymous"></script>
        <!-- Plugin datatables-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'lib/datatables_min/datatables.min.css' %}"/>
        <script type="text/javascript"
                src="{% static 'lib/datatables_min/datatables.min.js' %}"></script>
        <!-- Plugin SweetAlert 2-->
        <script src="{% static 'lib/sweetalert_2_min/sweetalert2.all.min.js' %}"></script>
        <!-- Plugin Bootstrap 5.1.3-->
        <script src="{% static 'lib/bootstrap_v5.1.3_min/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    {% else %}
        <!-- Plugin datatables-->
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
        <link href="{% static 'lib/admin-bs5/css/styles.css' %}" rel="stylesheet"/>
        <script src="https://use.fontawesome.com/releases/v6.1.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Plugin datatables-->
        <link rel="stylesheet" type="text/css"
              href="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-html5-2.2.2/datatables.min.css"/>
        <script type="text/javascript"
                src="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-html5-2.2.2/datatables.min.js"></script>
        <!-- Plugin SweetAlert 2-->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.8/dist/sweetalert2.all.min.js"></script>
        <!-- Plugin Bootstrap 5.1.3-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                crossorigin="anonymous"></script>
    {% endif %}
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="index.html"><i class="fa-solid fa-robot fa-xl"></i>&nbsp;&nbsp;Robot Control</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
{#    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">#}
{#        <div class="input-group">#}
{#            <input class="form-control" type="text" placeholder="Buscar por..." aria-label="Search for..."#}
{#                   aria-describedby="btnNavbarSearch"/>#}
{#            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>#}
{#        </div>#}
{#    </form>#}
    <!-- Navbar-->
{#    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4 text-end">#}
{#        <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"#}
{#               aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>#}
{#            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">#}
{#                <li><a class="dropdown-item" href="#!">Settings</a></li>#}
{#                <li><a class="dropdown-item" href="#!">Activity Log</a></li>#}
{#                <li>#}
{#                    <hr class="dropdown-divider"/>#}
{#                </li>#}
{#                <li><a class="dropdown-item" href="#!">Logout</a></li>#}
{#            </ul>#}
{#        </li>#}
{#    </ul>#}
</nav>
<div id="layoutSidenav">

    {% include 'navbar_base.html' %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">
                <h1 class="mt-3 mb-3">{{ title }}</h1>
                {#                <ol class="breadcrumb mb-4">#}
                {#                    <li class="breadcrumb-item active">Dashboard</li>#}
                {#                </ol>#}
                {% block contenido %}

                {% endblock %}
            </div>
            {% csrf_token %}
        </main>
        {% include 'footer_base.html' %}
    </div>
</div>
<script src="{% static 'lib/admin-bs5/js/scripts.js' %}"></script>
{% if debug_value %}
    <script src="{% static 'js/complementos_bs/Chart.min_bs.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/complementos_bs/simple-datatables@latest.js' %}" crossorigin="anonymous"></script>
{% else %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
{% endif %}

{% block scripts %}

{% endblock %}
</body>
</html>

ControlRemoto/templates/footer_base.html
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
{#            <div class="text-muted">Copyright &copy; Robot Control 2022</div>#}
            <div>
{#                <a href="#">Privacy Policy</a>#}
{#                &middot;#}
{#                <a href="#">Terms &amp; Conditions</a>#}
            </div>
        </div>
    </div>
</footer>

ControlRemoto/templates/navbar_base.html
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Opciones</div>
                <a class="nav-link {{ dashboard }}" href="{% url 'control_remoto:control_remoto' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt fa-xl"></i></div>
                    Control Remoto
                </a>
                <a class="nav-link {{ ajuste_pid }}" href="{% url 'control_remoto:ajuste_pid' %}">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-sliders fa-xl"></i></div>
                    Ajuste PID
                </a>
                <a class="nav-link {{ nav_robot }}" href="{% url 'control_remoto:nav_robot' %}">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-car-on fa-xl"></i></div>
                    Navegar Entorno
                </a>
{#                <div class="sb-sidenav-menu-heading">Interface</div>#}
{#                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts"#}
{#                   aria-expanded="false" aria-controls="collapseLayouts">#}
{#                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>#}
{#                    Layouts#}
{#                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>#}
{#                </a>#}
{#                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"#}
{#                     data-bs-parent="#sidenavAccordion">#}
{#                    <nav class="sb-sidenav-menu-nested nav">#}
{#                        <a class="nav-link" href="layout-static.html">Static Navigation</a>#}
{#                        <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>#}
{#                    </nav>#}
{#                </div>#}
{#                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"#}
{#                   aria-expanded="false" aria-controls="collapsePages">#}
{#                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>#}
{#                    Pages#}
{#                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>#}
{#                </a>#}
{#                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo"#}
{#                     data-bs-parent="#sidenavAccordion">#}
{#                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">#}
{#                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"#}
{#                           data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">#}
{#                            Authentication#}
{#                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>#}
{#                        </a>#}
{#                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne"#}
{#                             data-bs-parent="#sidenavAccordionPages">#}
{#                            <nav class="sb-sidenav-menu-nested nav">#}
{#                                <a class="nav-link" href="login.html">Login</a>#}
{#                                <a class="nav-link" href="register.html">Register</a>#}
{#                                <a class="nav-link" href="password.html">Forgot Password</a>#}
{#                            </nav>#}
{#                        </div>#}
{#                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"#}
{#                           data-bs-target="#pagesCollapseError" aria-expanded="false"#}
{#                           aria-controls="pagesCollapseError">#}
{#                            Error#}
{#                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>#}
{#                        </a>#}
{#                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne"#}
{#                             data-bs-parent="#sidenavAccordionPages">#}
{#                            <nav class="sb-sidenav-menu-nested nav">#}
{#                                <a class="nav-link" href="401.html">401 Page</a>#}
{#                                <a class="nav-link" href="404.html">404 Page</a>#}
{#                                <a class="nav-link" href="500.html">500 Page</a>#}
{#                            </nav>#}
{#                        </div>#}
{#                    </nav>#}
{#                </div>#}
{#                <div class="sb-sidenav-menu-heading">Addons</div>#}
{#                <a class="nav-link" href="charts.html">#}
{#                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>#}
{#                    Charts#}
{#                </a>#}
{#                <a class="nav-link" href="tables.html">#}
{#                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>#}
{#                    Tables#}
{#                </a>#}
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Conectado como:</div>
            {{ request.user.username }}
        </div>
    </nav>
</div>